### ISSUE TITLE
Encoding issue when processing this on service fabric cluster

### ISSUE THREAD

**Issue by JelleBroekhuijsen** [Azure-Samples/compute-automation-configurations#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks

When following these steps the script gets downloaded to the service fabric nodes. However since the latest commit the script contains bad characters which break script execution.

### Any log messages given by the failure
>
Script execution halts on bad characters.

### Expected/desired behavior
>
Script execution performs its tasks.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Service Fabric Stack latest release

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JelleBroekhuijsen** [comment]
I also verified that the bad character issue is not limited to service fabric, if I clone the current version of the script on windows 10 and open it with PowerShell ISE the same problem occurs.

**Comment by harelhadar** [comment]
I have the same issue with VMSS Managed Disk and Service Fabric.
As you said there is a problem with the last commit, meanwhile I use the script with link to previous version:
https://raw.githubusercontent.com/Azure-Samples/compute-automation-configurations/fdc643759c9aa7e9259da10575e67dc1368e4e9f/prepare_vm_disks.ps1

```
{
    "name": "customScript",
    "properties": {
        "publisher": "Microsoft.Compute",
        "type": "CustomScriptExtension",
        "typeHandlerVersion": "1.8",
        "autoUpgradeMinorVersion": true,
        "settings": {
        "fileUris": [
            "https://https://raw.githubusercontent.com/Azure-Samples/compute-automation-configurations/fdc643759c9aa7e9259da10575e67dc1368e4e9f/prepare_vm_disks.ps1"
        ],
        "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File prepare_vm_disks.ps1"
        }
    }
}
```

**Comment by sridmad** [comment]
This is resolved with above commit
