### ISSUE TITLE
log: command not found

### ISSUE THREAD

**Issue by raidlman** [Azure-Samples/compute-automation-configurations#8]
When using the `prepare_vm_disks.sh` script with a Azure VM CustomScript extension together with one of the "non official" Linux images in the marketplace I get the following error:

    ./prepare_vm_disks.sh: line 140: log: command not found
    ./prepare_vm_disks.sh: line 146: log: command not found

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a:
```
- [x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Create a custom script extension with the following settings section:

    {
      "fileUris": ["https://raw.githubusercontent.com/Azure-Samples/compute-automation-configurations/master/prepare_vm_disks.sh"],
      "commandToExecute": "./prepare_vm_disks.sh"
    }

### Any log messages given by the failure

    ./prepare_vm_disks.sh: line 140: log: command not found
    ./prepare_vm_disks.sh: line 146: log: command not found

### Expected/desired behavior

Either use standard Shell commands for logging or include log function in script.

### OS and Version?

    publisher = "azurecyclecloud"
    offer     = "azure-cyclecloud-vm"
    sku       = "cyclecloud-77"
    version   = "7.7.3"

Image is based on CentOS 7.5

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by iainfoulds** [comment]
Sorry you ran into issues, @raidlman.

This has been updated in https://github.com/Azure-Samples/compute-automation-configurations/pull/9
